### ISSUE TITLE
Pipeline crashes at startup

### ISSUE THREAD

**Issue by louis-youpling** [timeflux/timeflux_ui#1]
Pipeline crashed after opening localhost:8000 in the browser. Logs are :
 
```
2019-04-23 18:39:40,860    ERROR      scheduler    12784    Viz              DataFrame index must be unique for orient='index'.
Traceback (most recent call last):
  File "c:\users\louis\.conda\envs\timeflux\lib\site-packages\timeflux\core\scheduler.py", line 22, in run
    self.next()
  File "c:\users\louis\.conda\envs\timeflux\lib\site-packages\timeflux\core\scheduler.py", line 61, in next
    self._nodes[step['node']].update()
  File "c:\users\louis\.conda\envs\timeflux\lib\site-packages\timeflux_ui\nodes\ui.py", line 125, in update
    'samples': self._convert(port.data)
  File "c:\users\louis\.conda\envs\timeflux\lib\site-packages\timeflux_ui\nodes\ui.py", line 110, in _convert
    data = data.to_dict(orient='index') # export to dict
  File "c:\users\louis\.conda\envs\timeflux\lib\site-packages\pandas\core\frame.py", line 1316, in to_dict
    "DataFrame index must be unique for orient='index'."
ValueError: DataFrame index must be unique for orient='index'.
```

**Comment by louis-youpling** [comment]
@mesca I have logged this issue here as it seem to relate specifically to timeflux_ui

**Comment by mesca** [comment]
Already fixed in https://github.com/timeflux/timeflux_ui/commit/168d0247d8fa50c675af0d3d0ccebe62dbef05a2 ;)
